name: build-and-push-docker-images-all

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'upload-results-s3.sh'

jobs:
  call-workflow-passing-data-gitleaks:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: gitleaks
    secrets: inherit

  call-workflow-passing-data-semgrep:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: semgrep
    secrets: inherit

  call-workflow-passing-data-trivy:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: trivy
    secrets: inherit

  call-workflow-passing-data-zap:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: zap
    secrets: inherit

  call-workflow-passing-data-github-ddt:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: github-ddt
    secrets: inherit
