name: build-and-push-docker-images-github-ddt

on:
  push:
    branches:
      - "main"
    paths:
      - 'github-ddt/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: github-ddt
    secrets: inherit
